In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegressionCV
from sklearn.cross_validation import train_test_split

/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv('final.csv').iloc[:,3:]

In [3]:
X =  df.iloc[:, 1:]
y = df.iloc[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [4]:
classifier = LogisticRegressionCV(random_state=101)
classifier.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=101,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [5]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  2  19   0  38]
 [  0  17   0  94]
 [  0  12   0  84]
 [  0   5   0 473]]


In [6]:
from sklearn import metrics

In [7]:
print(metrics.classification_report(y_test, y_pred))
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

             precision    recall  f1-score   support

          1       1.00      0.03      0.07        59
          2       0.32      0.15      0.21       111
          3       0.00      0.00      0.00        96
          4       0.69      0.99      0.81       478

avg / total       0.57      0.66      0.56       744

Accuracy of logistic regression classifier on test set: 0.66


/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
from sklearn.utils import resample

In [9]:
df_majority = df[df.Target==4]
df_minority1 = df[df.Target==1]
df_minority2 = df[df.Target==2]
df_minority3 = df[df.Target==3]

In [10]:
df_minority1_upsampled = resample(df_minority1, 
                                 replace=True,     # sample with replacement
                                 n_samples=1954,    # to match majority class
                                 random_state=123) # reproducible results
df_minority2_upsampled = resample(df_minority2, 
                                 replace=True,     # sample with replacement
                                 n_samples=1954,    # to match majority class
                                 random_state=123) # reproducible results
df_minority3_upsampled = resample(df_minority3, 
                                 replace=True,     # sample with replacement
                                 n_samples=1954,    # to match majority class
                                 random_state=123) # reproducible results


In [11]:
df_upsampled = pd.concat([df_majority, df_minority1_upsampled, df_minority2_upsampled, df_minority3_upsampled])

In [12]:
len(df_upsampled)

7816

In [13]:
X =  df_upsampled.iloc[:, 1:]
y = df_upsampled.iloc[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
classifier = LogisticRegressionCV(random_state=101)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

In [ ]:
from sklearn import metrics

In [ ]:
print(metrics.classification_report(y_test, y_pred))
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, y_pred)))

In [ ]:
df_majority = df[df.Target==4]
df_minority = df[df.Target!=4]

In [ ]:
df_majority_downsampled = resample(df_majority, 
                                 replace=True,     # sample with replacement
                                 n_samples=340,    # to match majority class
                                 random_state=123) # reproducible results

In [ ]:
df_downsampled = pd.concat([df_majority_downsampled, df_minority])

In [ ]:
X =  df_upsampled.iloc[:, 1:]
y = df_upsampled.iloc[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
classifier = LogisticRegressionCV(random_state=101)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

In [ ]:
from sklearn import metrics

In [ ]:
print(metrics.classification_report(y_test, y_pred))
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, y_pred)))

In [ ]:
df_upsampled.to_csv("final-upsampled.csv", index = None)

In [ ]:
df_downsampled.to_csv("final-downsampled.csv", index = None)